. /etc/X11/xinit/xinitrc.d/*
. /etc/X11/xinit/xinitrc-common

gnome-keyring-daemon

eval $(gpg-agent --daemon)
export GPG_AGENT_INFO
keychain

urxvt256cd &
xscreensaver &
xbindkeys &
xsetroot -cursor_name left_ptr
#awsetbg -r "/srv/pictures/Wallpapers 2560x1440"

export BROWSER="`which google-chrome`"

google-musicmanager

exec -l $SHELL -c "$SSH_AGENT /usr/bin/awesome"
