" tabs and indenting
set shiftwidth=4
set tabstop=8
set expandtab
set smarttab
set backspace=indent,eol,start
set autoindent

" syntax highlighting
syntax on
filetype on
filetype plugin on
filetype indent on
au BufNewFile,BufRead *.wsgi set filetype=python

" search
set incsearch
set hlsearch
set ignorecase
set smartcase

" we're on unix people
set fileformats=unix

" no annoying bells when the keyboard is mashed
set noerrorbells

" change <leader> ` to ,
let mapleader = ","

" catch trailing whitespace on ,s
nmap <silent> <leader>s :set nolist!<CR>

command Wq wq

" some random settings
set ruler
set notitle
set pastetoggle=<F5>
set autowrite

" solarized colourscheme
set background=dark
colorscheme solarized

" bash-style tabcomp
set wildmenu
set wildmode=list:longest

" recurse upwards for ctags
set tags=./tags;

" pathogen
execute pathogen#infect()

" vim-easytags
let g:easytags_async = 1
let g:easytags_dynamic_files = 1

hi Normal ctermbg=none

let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
