# don't source for interactive shells
if [[ $- != *i* ]] ; then
    return
fi

if [ -r /etc/bashrc ] ; then
    source /etc/bashrc
elif [ -r /etc/bash.bashrc ] ; then
    source /etc/bash.bashrc
fi

export EDITOR="/usr/bin/vim"
export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] "
export PGUSER="postgres"
export TERM="xterm-256color"
export COLORTERM="urxvt256cc"

export GPGKEY=482EFAF8

export HISTFILESIZE="5000"
export HISTCONTROL="ignoreboth"
export PROMPT_COMMAND="history -a"
shopt -s histappend

if [ -d ~/dotfiles/bin ] ; then
    export PATH="$PATH:$HOME/dotfiles/bin"
fi
if [ -d ~/bin ] ; then
    export PATH="$PATH:$HOME/bin"
fi
if [ -d ~/scripts ] ; then
    export PATH="$PATH:$HOME/scripts"
fi
if [ -d ~/android-sdk ] ; then
    export PATH="$PATH:$HOME/android-sdk/tools:$HOME/android-sdk/platform-tools:$HOME/android-sdk/android-studio/bin"
fi
if [ -d /opt/bin ] ; then
    export PATH="$PATH:/opt/bin"
fi
if [ -d /opt/crosstool-ng ] ; then
    export PATH="$PATH:/opt/crosstool-ng/bin"
fi

if [ -d ~/webapps ] ; then
    export WORKON_HOME=~/webapps
    which virtualenvwrapper.sh >/dev/null 2>&1
    if [ $? -eq 0 ] ; then
        source `which virtualenvwrapper.sh`
    fi
fi

if [ -r ~/.pythonrc ] ; then
    export PYTHONSTARTUP=~/.pythonrc
fi

alias df="df -h"
alias grep="grep --color"
alias ll="ls -Fhl"
alias lsa="ls -aFhl"
alias rm="rm -i"
alias w="w -f"

shopt -s cdspell
shopt -s checkwinsize

# 4M core dumps please
ulimit -c 4000
